<a href="https://colab.research.google.com/github/HOSSENkhodadadi/Bachelors-Thesis/blob/main/Data_Science_Labs_Process_Methods/Exercises/4_Pandas_Examples.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

***Some tests on Series in Pandas***

In [ ]:
#creation
import pandas as pd
s1 = pd.Series([2,3.1,4.5])
s1


0    2.0
1    3.1
2    4.5
dtype: float64

In [ ]:
#creation from lists
pd.Series([2,3.1,4.5],index = ['mon','tue','wed'])

mon    2.0
tue    3.1
wed    4.5
dtype: float64

In [ ]:
#creaiton from dictionaries
pd.Series({'c':2.0,"b":4.1,'a':4.3})

c    2.0
b    4.1
a    4.3
dtype: float64

In [ ]:
a = {'c':2.0,"b":4.1,'a':4.3}
type(a.values())

dict_values

In [ ]:
s1 = pd.Series([2,3.1,4.5],index = ['mon','tue','wed'])
print(s1.values)
print(s1.index)

[2.  3.1 4.5]
Index(['mon', 'tue', 'wed'], dtype='object')


In [ ]:
s1 = pd.Series([2.0, 3.1, 4.5], index=['a', 'b', 'c'])
print(s1.loc['a'])
print(s1.iloc[0])
s1.loc['b'] = 10 # allows editing values

print(f"Series:\n{s1}")

2.0
2.0
Series:
a     2.0
b    10.0
c     4.5
dtype: float64


In [ ]:
#accessing elements: slicing
s1 = pd.Series([2.0, 3.1, 4.5], index=['a', 'b', 'c'])
print(s1.loc["b":'c']) #stop element included
print(s1.iloc[0:2])#stop element excluded

b    3.1
c    4.5
dtype: float64
a    2.0
b    3.1
dtype: float64


In [ ]:
# accessing series elements: masking
s1 = pd.Series([2.0, 3.1, 4.5], index=['a', 'b', 'c'])
s1[(s1 >2) & (s1<10)]

b    3.1
c    4.5
dtype: float64

In [ ]:
# accessing series elements: fancy indexing
s1 = pd.Series([2.0, 3.1, 4.5], index=['a', 'b', 'c'])
print(s1.loc[['a','b']])
print(s1.iloc[[0,2]])

a    2.0
b    3.1
dtype: float64
a    2.0
c    4.5
dtype: float64


***Pandas DataFrames***

In [ ]:
# Creation from Series
price = pd.Series([1.0, 1.4, 5], index=['a', 'b', 'c'])
quantity = pd.Series([5, 10, 8], index=['a', 'b', 'c'])
liters = pd.Series([1.5, 0.3, 1], index=['a', 'b', 'c'])
print(type(liters))
df = pd.DataFrame({'Price': price, "Quantitiy": quantity, 'Liters':liters})
df


<class 'pandas.core.series.Series'>


Price  Quantitiy  Liters
a    1.0          5     1.5
b    1.4         10     0.3
c    5.0          8     1.0

In [ ]:
# Creation from Dictionaries
dct = {"c1": [0,1,2],"c2": [0,2,4]}
df = pd.DataFrame(dct)
df


c1  c2
0   0   0
1   1   2
2   2   4

In [ ]:
# Creation from list of Dictionaries
dic_list = [{'c1':i, 'c2': 2*i} for i in range(3)]
df = pd.DataFrame(dic_list)
df

c1  c2
0   0   0
1   1   2
2   2   4

In [ ]:
import numpy as np
#creation from 2D numpy array
arr = np.arange(6).reshape((3,2))
df = pd.DataFrame(arr, columns = ['c1','c2'], index = ['a','b', 'c'])
print(df)

   c1  c2
a   0   1
b   2   3
c   4   5


In [ ]:
# Reading and writing a csv file
dct = {'c1':[0,1, 'no info'], "c2": [0,2,"NaN"], 'c3': ['x',5,""]}
df = pd.DataFrame(dct)
df.to_csv('test.csv', sep = ',',index = False)


dd = pd.read_csv('test.csv', sep = ',',na_values = ['no info', 'x'], skiprows =0)
print(dd)

    c1   c2   c3
0  0.0  0.0  NaN
1  1.0  2.0  5.0
2  NaN  NaN  NaN


In [ ]:
# How to write a json file
import json

myJason = {"c1":{"0":0, "1":3, "2":6},
"c2":{"0":"null", "1":4, "2":"null"},
"c3":{"0":2, "1":5, "2":"null"}}
print(type(myJason))

json_object = json.dumps(myJason)
with open('myJason.json','w') as outfile:
  outfile.write (json_object)

In [ ]:
# write and read to json
df = pd.read_json('myJason.json')
print(df)
dct = {'a':[1,2,3],"b":[4,5,6],'c':[7,8,9]}

df = pd.DataFrame(dct)
print(f"this is the df that is going to be json file: \n {df}")
df.to_json('dfToJson')



   c1    c2    c3
0   0  null     2
1   3     4     5
2   6  null  null
this is the df that is going to be json file: 
    a  b  c
0  1  4  7
1  2  5  8
2  3  6  9


In [ ]:
price = pd.Series([1.0, 1.4, 5], index=['a', 'b', 'c'])
quantity = pd.Series([5, 10, 8], index=['a', 'b', 'c'])
liters = pd.Series([1.5, 0.3, 1], index=['a', 'b', 'c'])

df = pd.DataFrame({'Price': price, "Quantity": quantity, 'Liters':liters})
print (df)
print(df.columns)
print(df.index)
print(df.values) #returns numpy array
print(df['Quantity'])#accessing columns
print(f"this is the row a: \n{df.loc['a']}")# accessing rows
print(df.iloc[0])
print(df.loc['b':'c', 'Quantity': "Liters"])# slicing

   Price  Quantity  Liters
a    1.0         5     1.5
b    1.4        10     0.3
c    5.0         8     1.0
Index(['Price', 'Quantity', 'Liters'], dtype='object')
Index(['a', 'b', 'c'], dtype='object')
[[ 1.   5.   1.5]
 [ 1.4 10.   0.3]
 [ 5.   8.   1. ]]
a     5
b    10
c     8
Name: Quantity, dtype: int64
this is the row a: 
Price       1.0
Quantity    5.0
Liters      1.5
Name: a, dtype: float64
Price       1.0
Quantity    5.0
Liters      1.5
Name: a, dtype: float64
   Quantity  Liters
b        10     0.3
c         8     1.0


In [ ]:
price = pd.Series([1.0, 1.4, 5], index=['a', 'b', 'c'])
quantity = pd.Series([5, 10, 8], index=['a', 'b', 'c'])
liters = pd.Series([1.5, 0.3, 1], index=['a', 'b', 'c'])
df = pd.DataFrame({'Price': price, "Quantity": quantity, 'Liters':liters})

#masking
mask = (df['Quantity'] < 10) & (df["Liters"] > 1)
df.loc[mask, "Quantity":]

Quantity  Liters
a         5     1.5

In [ ]:
price = pd.Series([1.0, 1.4, 5], index=['a', 'b', 'c'])
quantity = pd.Series([5, 10, 8], index=['a', 'b', 'c'])
liters = pd.Series([1.5, 0.3, 1], index=['a', 'b', 'c'])

df = pd.DataFrame({'Price': price, "Quantity": quantity, 'Liters':liters})

#fancy indexing
# there is a difference between pandas and numpy fancy indexing here

print(df.loc[['a','c'],["Price", "Liters"]])

import numpy as np
nm = np.arange(1,10).reshape(3,3)
print(nm)
nm[[0,1],[1,2]]



   Price  Liters
a    1.0     1.5
c    5.0     1.0
[[1 2 3]
 [4 5 6]
 [7 8 9]]
 iman code goes here: 
 


<ipython-input-12-a1354d759e5d>:18: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  nm[[[0, 1,0], [1, 2,0]]]


array([2, 6, 1])

In [ ]:
df.loc[['a','c'],["Price", "Liters"]] = 0
print(df)

   Price  Quantity  Liters
a    0.0         5     0.0
b    1.4        10     0.3
c    0.0         8     0.0


In [ ]:
# add a new column
df['availability'] = pd.Series([True,False,True], index = ['a','b','c'])
df['Accessibility'] = [1.,2, 45]
print(df)

   Price  Quantity  availability  Accessibility
a    0.0         5          True            1.0
b    1.4        10         False            2.0
c    0.0         8          True           45.0


In [ ]:
#drop columns if inplace = False returns a copy else returns modifies the orginal df

#df.drop(columns = ['availability', "Accessibility"], inplace = True)
#df

plate = df.drop(columns = ['availability', "Accessibility"])
print(plate)

   Price  Quantity
a    0.0         5
b    1.4        10
c    0.0         8


In [ ]:
# rename columns  dictionary  = {"old name": 'new Name",...}
df = df.rename(columns = {'Quantity': 'nItems', "availability": '[L]'})
df

Price  nItems    [L]  Accessibility
a    0.0       5   True            1.0
b    1.4      10  False            2.0
c    0.0       8   True           45.0

In [ ]:
# unary functions and Pandas
price = pd.Series([1.0, 1.4, 5], index=['a', 'b', 'c'])
quantity = pd.Series([5, 10, 8], index=['a', 'b', 'c'])
liters = pd.Series([1.5, 0.3, 1], index=['a', 'b', 'c'])
myDataFrame = pd.DataFrame({'Price': price, "Quantity": quantity, 'Liters':liters})

mySeries = pd.Series([2.0,-4,6])
res = mySeries/4 +1
res = np.abs (mySeries)
res = np.exp(mySeries)
res = np.sin(mySeries/4)



0    0.479426
1   -0.841471
2    0.997495
dtype: float64

In [ ]:
# Operation between dataFrames all columns and indices are the same
Total  = pd.Series([3,1,10], index = ['a', 'b', 'c'])
Quantity = pd.Series([4,2,20], index = ['a', 'b', 'c'])
df1 = pd.DataFrame({"Total": Total,"Quantity": Quantity})

Total  = pd.Series([1,3,30], index = ['a', 'b', 'c'])
Quantity = pd.Series([2,4,40], index = ['a', 'b', 'c'])
df2 = pd.DataFrame({"Total": Total,"Quantity": Quantity})

res = df1 + df2
res

Total  Quantity
a      4         6
b      4         6
c     40        60

In [ ]:
# Operation between dataFrames including different columns and indices are the same
Total  = pd.Series([3,1,10], index = ['a', 'b', 'c'])
Quantity = pd.Series([4,2,20], index = ['a', 'b', 'c'])
df1 = pd.DataFrame({"Total": Total,"Quantity": Quantity})

Total  = pd.Series([1,3,30], index = ['a', 'b', 'c'])
Price = pd.Series([2,4,40], index = ['a', 'b', 'c'])
df2 = pd.DataFrame({"Total": Total,"Price": Price})

#columns are sorted after operation
res = df1 + df2
print(res)

   Price  Quantity  Total
a    NaN       NaN      4
b    NaN       NaN      4
c    NaN       NaN     40


In [ ]:
# Operation between dataFrame and Series including/excluding different columns
Total  = pd.Series([3,1,10], index = ['a', 'b', 'c'])
Quantity = pd.Series([4,2,20], index = ['a', 'b', 'c'])
df1 = pd.DataFrame({"Total": Total,"Quantity": Quantity})

s1 = pd.Series([1,2], index = ["Total", "Quantity"])

res = df1 + s1# follows broadcasting rules
print(res,"\n")
#------------------------------------------------------------------------------
Total  = pd.Series([3,1,10], index = ['a', 'b', 'c'])
Quantity = pd.Series([4,2,20], index = ['a', 'b', 'c'])
df1 = pd.DataFrame({"Total": Total,"Quantity": Quantity})

s2 = pd.Series([1,2], index = ["Total", "Price"])#different index

res = df1 + s2# follows broadcasting rules
print(res,"\n")
#------------------------------------------------------------------------------
Total  = pd.Series([3,1,10], index = ['a', 'b', 'c'])
Quantity = pd.Series([4,2,20], index = ['a', 'b', 'c'])
df2 = pd.DataFrame({"Total": Total,"Price": Quantity}) #different columns

s1 = pd.Series([1,2], index = ["Total", "Quantity"])

res = df2 + s1# follows broadcasting rules
print(res,"\n")




   Total  Quantity
a      4         6
b      2         4
c     11        22 

   Price  Quantity  Total
a    NaN       NaN    4.0
b    NaN       NaN    2.0
c    NaN       NaN   11.0 

   Price  Quantity  Total
a    NaN       NaN    4.0
b    NaN       NaN    2.0
c    NaN       NaN   11.0 



In [ ]:
# Operation between dataFrames including different columns and indices are the same
Total  = pd.Series([3,1,10], index = ['a', 'b', 'c'])
Quantity = pd.Series([4,2,20], index = ['a', 'b', 'c'])
df1 = pd.DataFrame({"Total": Total,"Quantity": Quantity})

Total  = pd.Series([1,3], index = ['a', 'b'])
Quantity = pd.Series([2,4], index = ['a', 'b'])
df2 = pd.DataFrame({"Total": Total,"Quantity": Quantity})

print(df1, "\n")
print(df2, "\n")
#columns are sorted after operation
res = df1 + df2
print(res)

   Total  Quantity
a      3         4
b      1         2
c     10        20 

   Total  Quantity
a      1         2
b      3         4 

   Total  Quantity
a    4.0       6.0
b    4.0       6.0
c    NaN       NaN


In [ ]:
#operations on Series
s1 = pd.Series([1,2,3], index = ['a','b','c'])
print(s1.mean())
print(s1.max())
print(s1.std())
print(s1.sum())

2.0
3
1.0
6


In [ ]:
price = pd.Series([1.0, 1.4, 5], index=['a', 'b', 'c'])
quantity = pd.Series([5, 10, 8], index=['a', 'b', 'c'])
liters = pd.Series([1.5, 0.3, 1], index=['a', 'b', 'c'])

df = pd.DataFrame({'Price': price, "Quantitiy": quantity, 'Liters':liters})
df.min() # retruns the function based on columns

# Z_score normalization

mean_series = df.mean()
std_series = df.std()
df_norm = (df- mean_series)/std_series
df_norm

Price  Quantitiy    Liters
a -0.665750  -1.059626  0.940102
b -0.484182   0.927173 -1.050702
c  1.149932   0.132453  0.110600

In [ ]:
# Missing Values
print(type(None))
# None is an object
print(type(np.nan))
# np.nan acheieves better performance since it is a floating point number dude

# Pandas supports both and converts them when necessary
s1 = pd.Series([4, None, 5, np.nan])
print(s1.isnull(),"\n")
print(s1.notnull(),"\n")



<class 'NoneType'>
<class 'float'>
0    False
1     True
2    False
3     True
dtype: bool 

0     True
1    False
2     True
3    False
dtype: bool 

0    4.0
2    5.0
dtype: float64 



In [ ]:
# remove nan from series
s1 = pd.Series([1,np.nan, 5, None, 46])
#print(s1,'\n')

s1.dropna(inplace = True)
# Or
s2 = s1.dropna()


0     1.0
2     5.0
4    46.0
dtype: float64

In [ ]:
price = pd.Series([1.0, np.nan, 5], index=['a', 'b', 'c'])
quantity = pd.Series([5, 10, None], index=['a', 'b', 'c'])
liters = pd.Series([1.5, 0.3, 1], index=['a', 'b', 'c'])

df = pd.DataFrame({'Price': price, "Quantitiy": quantity, 'Liters':liters})
print(f"this is the main df{df} \n")

df_row = df.dropna() #removes all the rows including nan entities inplace = True
print(f"df wihtout rows including nan{df_row}\n")

dropped_df = df.dropna(axis = 'columns')
print(f"df without columns including nan {dropped_df}\n")


this is the main df   Price  Quantitiy  Liters
a    1.0        5.0     1.5
b    NaN       10.0     0.3
c    5.0        NaN     1.0 

df wihtout rows including nan   Price  Quantitiy  Liters
a    1.0        5.0     1.5

df without columns including nan    Liters
a     1.5
b     0.3
c     1.0



In [ ]:
s1 = pd.Series([1,np.nan, 5, None, 46])
#s1 = s1.fillna(0)
s1.fillna(0, inplace = True)
s1



0     1.0
1     0.0
2     5.0
3     0.0
4    46.0
dtype: float64

In [ ]:
s1 = pd.Series([1,np.nan, 5, None, 46])
s2 = s1.fillna(method = 'ffill')
print(s2)

s3 = s1.fillna(method = 'bfill')
s3

0     1.0
1     1.0
2     5.0
3     5.0
4    46.0
dtype: float64


0     1.0
1     5.0
2     5.0
3    46.0
4    46.0
dtype: float64

In [ ]:
# what about dynamic averageing


In [ ]:
# concatinating series
s1 = pd.Series(['a', "b"], index = [1,2])
s2 = pd.Series(['c', "d"], index = [1,2])

print(pd.concat((s1,s2)))
pd.concat((s1,s2), ignore_index= True)


1    a
2    b
1    c
2    d
dtype: object


0    a
1    b
2    c
3    d
dtype: object

In [ ]:
price = pd.Series([1.0, np.nan, 5], index=['a', 'b', 'c'])
quantity = pd.Series([5, 10, None], index=['a', 'b', 'c'])
liters = pd.Series([1.5, 0.3, 1], index=['a', 'b', 'c'])

df1 = pd.DataFrame({'Price': price, "Quantitiy": quantity, 'Liters':liters})
print(df1)

price = pd.Series([1.0, np.nan, 5], index=['a', 'b', 'c'])
quantity = pd.Series([5, 10, None], index=['a', 'b', 'c'])
liters = pd.Series([15, 0.3, 1], index=['a', 'b', 'c'])

df2 = pd.DataFrame({'Price': price, "Quantitiy": quantity, 'Liters':liters})
print(df2)

pd.concat((df1,df2))

   Price  Quantitiy  Liters
a    1.0        5.0     1.5
b    NaN       10.0     0.3
c    5.0        NaN     1.0
   Price  Quantitiy  Liters
a    1.0        5.0    15.0
b    NaN       10.0     0.3
c    5.0        NaN     1.0


Price  Quantitiy  Liters
a    1.0        5.0     1.5
b    NaN       10.0     0.3
c    5.0        NaN     1.0
a    1.0        5.0    15.0
b    NaN       10.0     0.3
c    5.0        NaN     1.0

In [ ]:
# concat

price = pd.Series([1.0, np.nan, 5], index=['a', 'b', 'c'])
quantity = pd.Series([5, 10, None], index=['a', 'b', 'c'])
liters = pd.Series([1.5, 0.3, 1], index=['a', 'b', 'c'])

df1 = pd.DataFrame({'Price': price, "Quantitiy": quantity, 'Liters':liters})
print(df1)

price = pd.Series([1.0, np.nan, 5], index=['a', 'b', 'c'])
quantity = pd.Series([5, 10, None], index=['a', 'b', 'c'])

df2 = pd.DataFrame({'Price': price, "Quantitiy": quantity})
print(df2)

pd.concat((df1,df2))# missing columns are filled by NaN

   Price  Quantitiy  Liters
a    1.0        5.0     1.5
b    NaN       10.0     0.3
c    5.0        NaN     1.0
   Price  Quantitiy
a    1.0        5.0
b    NaN       10.0
c    5.0        NaN


Price  Quantitiy  Liters
a    1.0        5.0     1.5
b    NaN       10.0     0.3
c    5.0        NaN     1.0
a    1.0        5.0     NaN
b    NaN       10.0     NaN
c    5.0        NaN     NaN

In [ ]:
#append

price = pd.Series([1.0, np.nan, 5], index=['a', 'b', 'c'])
quantity = pd.Series([5, 10, None], index=['a', 'b', 'c'])
liters = pd.Series([1.5, 0.3, 1], index=['a', 'b', 'c'])

df1 = pd.DataFrame({'Price': price, "Quantitiy": quantity, 'Liters':liters})
print(df1)

price = pd.Series([1.0, np.nan, 5], index=['a', 'b', 'c'])
quantity = pd.Series([5, 10, None], index=['a', 'b', 'c'])
liters = pd.Series([15, 0.3, 1], index=['a', 'b', 'c'])

df2 = pd.DataFrame({'Price': price, "Quantitiy": quantity, 'Liters':liters})
print(df2)

df_concat = df1.append(df2) # df_concat = pd.concat((df1,df2))
df_concat

   Price  Quantitiy  Liters
a    1.0        5.0     1.5
b    NaN       10.0     0.3
c    5.0        NaN     1.0
   Price  Quantitiy  Liters
a    1.0        5.0    15.0
b    NaN       10.0     0.3
c    5.0        NaN     1.0


Price  Quantitiy  Liters
a    1.0        5.0     1.5
b    NaN       10.0     0.3
c    5.0        NaN     1.0
a    1.0        5.0    15.0
b    NaN       10.0     0.3
c    5.0        NaN     1.0

In [ ]:
price = pd.Series([1.0, 5], index=['a', 'b'])
quantity = pd.Series([5, 10], index=['a', 'b'])


df1 = pd.DataFrame({'Price': price, "Quantitiy": quantity})
print(df1)

price = pd.Series([1.0, 5], index=['a', 'b'])
quantity = pd.Series([5, 10], index=['a', 'b'])


df2 = pd.DataFrame({'Price': price, "somethingElse": quantity})
print(df2)

pd.merge(df1,df2)

   Price  Quantitiy
a    1.0          5
b    5.0         10
   Price  somethingElse
a    1.0              5
b    5.0             10


Price  Quantitiy  somethingElse
0    1.0          5              5
1    5.0         10             10

In [ ]:
price = pd.Series([1.0, 5], index=['a', 'b'])
quantity = pd.Series(["m", "n"], index=['a', 'b'])


df1 = pd.DataFrame({'Price': price, "Quantitiy": quantity})
print(df1)

price = pd.Series([5, 1.0], index=['a', 'b'])
quantity = pd.Series(["x","y"], index=['a', 'b'])


df2 = pd.DataFrame({'Price': price, "somethingElse": quantity})
print(df2)

pd.merge(df1,df2)  # considers price as primary key performs a one to one merge

   Price Quantitiy
a    1.0         m
b    5.0         n
   Price somethingElse
a    5.0             x
b    1.0             y


Price Quantitiy somethingElse
0    1.0         m             y
1    5.0         n             x

In [ ]:
price = pd.Series([0, 1,0,1.0], index=['a', 'b','c','d'])
quantity = pd.Series(["m", "n",'p','q'], index=['a', 'b','c','d'])


df1 = pd.DataFrame({'Price': price, "Quantitiy": quantity})
print(df1)

price = pd.Series([1.0, 0], index=['a', 'b'])
quantity = pd.Series(["x","y"], index=['a', 'b'])


df2 = pd.DataFrame({'Price': price, "somethingElse": quantity})
print(df2)

print(pd.merge(df1,df2, right_index=True, left_index=True))
pd.merge(df1,df2)# performs a many to one merge

   Price Quantitiy
a    0.0         m
b    1.0         n
c    0.0         p
d    1.0         q
   Price somethingElse
a    1.0             x
b    0.0             y
   Price_x Quantitiy  Price_y somethingElse
a      0.0         m      1.0             x
b      1.0         n      0.0             y


Price Quantitiy somethingElse
0    0.0         m             y
1    0.0         p             y
2    1.0         n             x
3    1.0         q             x

In [ ]:
df = pd.DataFrame({'k' : ['a','b','a','b'],
'c1': [2,10,3,15], 'c2' : [4,20,5,30]})
print (df)
grouped_df = df.groupby('k')

for key, group_df in grouped_df:
  print(key)
  print(group_df)

   k  c1  c2
0  a   2   4
1  b  10  20
2  a   3   5
3  b  15  30
a
   k  c1  c2
0  a   2   4
2  a   3   5
b
   k  c1  c2
1  b  10  20
3  b  15  30


In [ ]:
grouped_df.mean()# aggregation  for each group

c1    c2
k            
a   2.5   4.5
b  12.5  25.0

In [ ]:
grouped_df['c1'].mean()

k
a     2.5
b    12.5
Name: c1, dtype: float64

In [ ]:
#Keep groups for which columns c1 has a mean > 5
grouped_df.filter(lambda x:x['c1'].mean() > 5)
# the average for the a group is 2.5 les than 5 and the group b is 12.5

k  c1  c2
1  b  10  20
3  b  15  30

In [ ]:
df = pd.DataFrame({'type':['a','b','b','a','b','a','b','a'],
'class':[3,2,3,3,2,1,1,2],
'fail':[1,1,1,0,1,0,0,0]})

# number of failure
df.pivot_table('fail',index = 'type', columns = 'class', aggfunc = 'sum')
# percentage of failure
df.pivot_table('fail', index = 'type', columns = 'class', aggfunc = 'mean')

class    1    2    3
type                
a      0.0  0.0  0.5
b      0.0  1.0  1.0

In [ ]:

# building a multi_indexed Series
# allows specifying an index hierarchy for series DataFrames
import pandas as pd
ix = [['Rome', 'Rome', 'Turin', 'Turin'],
['2018', '2019', '2018', '2019']]
s1 = pd.Series([10,13,7,9], index = ix)
s1
s1 = s1.sort_index() #multi-index should be sorted if you want to use slicing
s1


Rome   2018    10
       2019    13
Turin  2018     7
       2019     9
dtype: int64

In [ ]:
s1.index.names = ["City", 'Year']
s1


City   Year
Rome   2018    10
       2019    13
Turin  2018     7
       2019     9
dtype: int64

In [ ]:
# Accessing index levels 
print(s1.loc['Rome'])
print(s1.loc[:, "2018"])

Year
2018    10
2019    13
dtype: int64
City
Rome     10
Turin     7
dtype: int64


In [ ]:
print(s1.loc['Turin','2018':'2019'])
print(s1[s1 > 10])

City   Year
Turin  2018    7
       2019    9
dtype: int64
City  Year
Rome  2019    13
dtype: int64


In [ ]:
import numpy as np
ix = [['Rome', 'Rome', 'Turin', 'Turin'],
['2018', '2019', '2018', '2019']]

cols = [['c1','c1','c2','c2'],['a','b','a','b']]
data = np.arange(16).reshape((4,4))
df = pd.DataFrame(data, index = ix, columns = cols)
df

c1      c2    
             a   b   a   b
Rome  2018   0   1   2   3
      2019   4   5   6   7
Turin 2018   8   9  10  11
      2019  12  13  14  15

In [ ]:
# Multi-indexed DataFrame-How to access with outer index level

print(df['c1'])
print(df.loc['Rome','c1' ])

             a   b
Rome  2018   0   1
      2019   4   5
Turin 2018   8   9
      2019  12  13
      a  b
2018  0  1
2019  4  5


In [ ]:
# Multi-indexed DataFrame-How to access with outer and inner index level

df['c1', 'a']

Rome   2018     0
       2019     4
Turin  2018     8
       2019    12
Name: (c1, a), dtype: int64

In [ ]:
# Multi-indexed DataFrame-How to access with outer and inner index level
ix = pd.IndexSlice

df.loc[ix['Rome','2018'], ix['c1':'c2', 'a']]


c1  a    0
c2  a    2
Name: (Rome, 2018), dtype: int64

In [ ]:
# Reset index
df.index.names = ['city','year']

df_reset = df.reset_index()
print(df_reset)

    city  year  c1      c2    
                 a   b   a   b
0   Rome  2018   0   1   2   3
1   Rome  2019   4   5   6   7
2  Turin  2018   8   9  10  11
3  Turin  2019  12  13  14  15


In [ ]:
# set index
df_reset.set_index(['city', 'year'])

c1      c2    
             a   b   a   b
city  year                
Rome  2018   0   1   2   3
      2019   4   5   6   7
Turin 2018   8   9  10  11
      2019  12  13  14  15

In [ ]:
ix = [['Rome','Rome', 'Turin','Turin'],[2018,2019,2018,2019]]
x = pd.Series([0,4,8,12], index = ix)
#x.set_index(['city','year']) #set_index only works for the Dataframes
x.index.names = ['city','year']
print(f"this is stacked x: \n \n{x}")
x.unstack()


this is stacked x: 
 
city   year
Rome   2018     0
       2019     4
Turin  2018     8
       2019    12
dtype: int64


year   2018  2019
city             
Rome      0     4
Turin     8    12

In [ ]:
# stack inverse function of unstack ! only works on DATA_FRAMES

price = pd.Series([1.0, 1.4, 5], index=['a', 'b', 'c'])
quantity = pd.Series([5, 10, 8], index=['a', 'b', 'c'])
liters = pd.Series([1.5, 0.3, 1], index=['a', 'b', 'c'])
unStackedDf = pd.DataFrame({'Price': price, "Quantity": quantity, 'Liters':liters})
print(unStackedDf)
print('\n')
unStackedDf.stack()


   Price  Quantity  Liters
a    1.0         5     1.5
b    1.4        10     0.3
c    5.0         8     1.0




a  Price        1.0
   Quantity     5.0
   Liters       1.5
b  Price        1.4
   Quantity    10.0
   Liters       0.3
c  Price        5.0
   Quantity     8.0
   Liters       1.0
dtype: float64

In [ ]:
import numpy as np
import pandas as pd
# Create the DataFrame again
ix = [['Rome', 'Rome', 'Turin', 'Turin'],
['2018', '2019', '2018', '2019']]

cols = [['c1','c1','c2','c2'],['a','b','a','b']]
data = np.arange(16).reshape((4,4))
df = pd.DataFrame(data, index = ix, columns = cols)
df.index.names = ['city', 'year']
df = df.reset_index()
df.set_index(['city','year'])


c1      c2    
             a   b   a   b
city  year                
Rome  2018   0   1   2   3
      2019   4   5   6   7
Turin 2018   8   9  10  11
      2019  12  13  14  15

In [ ]:
df.max (axis = 1, level = 0)

<ipython-input-5-e9b9fbb1bf89>:1: FutureWarning: Using the level keyword in DataFrame and Series aggregations is deprecated and will be removed in a future version. Use groupby instead. df.median(level=1) should use df.groupby(level=1).median().
  df.max (axis = 1, level = 0)


city  year  c1  c2
0   Rome  2018   1   3
1   Rome  2019   5   7
2  Turin  2018   9  11
3  Turin  2019  13  15

In [ ]:
df.max(level = 'city')

<ipython-input-6-5cd972130479>:1: FutureWarning: Using the level keyword in DataFrame and Series aggregations is deprecated and will be removed in a future version. Use groupby instead. df.median(level=1) should use df.groupby(level=1).median().
  df.max(level = 'city')


ValueError: ignored

In [ ]:
df.max(level = "year")

<ipython-input-7-d0c5c5a0e48d>:1: FutureWarning: Using the level keyword in DataFrame and Series aggregations is deprecated and will be removed in a future version. Use groupby instead. df.median(level=1) should use df.groupby(level=1).median().
  df.max(level = "year")


ValueError: ignored

# Pandas Examples

In [ ]:
# this is how unique function works
a = np.array([[1, 0, 0], [1, 4, 0], [2, 3, 4]])
print(a,"\n")
np.unique(a, axis=1, return_counts = True)

[[1 0 0]
 [1 4 0]
 [2 3 4]] 



(array([[0, 0, 1],
        [0, 4, 1],
        [4, 3, 2]]), array([1, 1, 1]))

In [ ]:
#find the first K closest points from test to train
import numpy as np
label = np.random.randint(0,5, size = 100)
X = np.random.random((100, 5))
X_test = np.random.random((10,5))
X.shape, Y.shape

((100, 5), (10, 5))

In [ ]:
# Here we calculate the distances
m =  (((X- X_test[0])**2).sum(axis = 1))**.5


In [ ]:
# lets suppose we want 5 nearest points
k = 5

In [ ]:
# it returns the position of the k = 5 nearest points
print(np.argsort(m)[:5])

# This is how to get the five closest points  
np.sort(m)[:5]

[78 79 90 36 92]


array([0.22052924, 0.32708094, 0.46249326, 0.47037469, 0.52521213])

In [ ]:
# Class of nearest points 
votes = label[np.argsort(m)[:5]]
#print(votes)
print(np.unique(votes, return_counts = True))
unique, counts = np.unique(votes, return_counts = True)
counts.max()
unique[counts.argmax()]
# two of the five nearest points are repeated in the same class(4) so probably
# point X_test[0] belongs to that class

(array([0, 1, 2, 4]), array([1, 1, 1, 2]))


4

In [ ]:
print(np.sort([5.1,4.9,7.2,1.3,0.1]))
print(np.argsort([5.1,4.9,7.2,1.3,0.1]))
np.argsort([5.1,4.9,7.2,1.3,0.1])[:2]

[0.1 1.3 4.9 5.1 7.2]
[4 3 1 0 2]


array([4, 3])

In [ ]:
distances = (((X-X-test[i])**2) \
.sum(axis = 1))**.5
k_nearest = distances.argsort(axis = 1)[:k]
votes = label[k_nearest]

NameError: ignored

In [ ]:
#Input data
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## 1) Accessing DataFrames and Series

In [ ]:


# Input table (12 samples x 4 attributes)
X = np.array([[5.1, 3.5, 1, 0.2],
           [4.3, 3. , 1, 0.1],
           [5. , np.nan, 1, 0.4],
           [5.1, 3.4, 2, 0.2],
           [7.0, 3.2, 1, 0.2],
           [6.9, 3.1, 3, 1.5],
           [6.7, 3.1, 1, np.nan],
           [6. , 2.9, 2, 1.5],
           [6.1, 3. , 2, 1.4],
           [6.5, 3. , 3, 2.2],
           [7.7, 3.8, 3, 2.2],
           [7.4, 2.8, 1, 1.9],
           [6.8, 3.2, 1, 2.3]])
# Column names
columns = ['height','width','intensity','weight']

# Class label of each sample
labels = np.array([0, 0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2])

**a) Create a DataFrame from a Numpy array (X)**
- Setup column names and the class label
- Add a new composite feature, 'area' = 'width' * 'height'
- Fix missing values with forward fill method

In [ ]:
df = pd.DataFrame(X, columns= columns)

df["area"] = df["height"]* df["width"]
df["Classes"] = labels
df.fillna(method = "ffill", inplace = True)
print(df)

    height  width  intensity  weight   area  Classes
0      5.1    3.5        1.0     0.2  17.85        0
1      4.3    3.0        1.0     0.1  12.90        0
2      5.0    3.0        1.0     0.4  12.90        0
3      5.1    3.4        2.0     0.2  17.34        0
4      7.0    3.2        1.0     0.2  22.40        0
5      6.9    3.1        3.0     1.5  21.39        1
6      6.7    3.1        1.0     1.5  20.77        1
7      6.0    2.9        2.0     1.5  17.40        1
8      6.1    3.0        2.0     1.4  18.30        1
9      6.5    3.0        3.0     2.2  19.50        2
10     7.7    3.8        3.0     2.2  29.26        2
11     7.4    2.8        1.0     1.9  20.72        2
12     6.8    3.2        1.0     2.3  21.76        2


In [ ]:
#Professors solution differs here
#df = pd.DataFrame(np.hstack([X, labels.reshape(-1,1)]), columns = columns +["label"] )
#df["area"] = df["width"]*df["height"]
#df.fillna(method = "ffill", inplace= True)
#df

height  width  intensity  weight  label   area
0      5.1    3.5        1.0     0.2    0.0  17.85
1      4.3    3.0        1.0     0.1    0.0  12.90
2      5.0    3.0        1.0     0.4    0.0  12.90
3      5.1    3.4        2.0     0.2    0.0  17.34
4      7.0    3.2        1.0     0.2    0.0  22.40
5      6.9    3.1        3.0     1.5    1.0  21.39
6      6.7    3.1        1.0     1.5    1.0  20.77
7      6.0    2.9        2.0     1.5    1.0  17.40
8      6.1    3.0        2.0     1.4    1.0  18.30
9      6.5    3.0        3.0     2.2    2.0  19.50
10     7.7    3.8        3.0     2.2    2.0  29.26
11     7.4    2.8        1.0     1.9    2.0  20.72
12     6.8    3.2        1.0     2.3    2.0  21.76

**b) Compute the average area of samples with intensity greater than 1:**

In [ ]:
df[df["intensity"]>1]["area"].mean()

#Professor's solution
#df[df["intensity"] > 1].mean()['area']

20.531666666666666

**c) Compute the following probability:**

$$P(label=2 \ | \ height<7)$$   

In [ ]:
p_intersection = (df[df["height"]< 7]["Classes"] == 2).sum()
p_denominator = (df["height"] < 7).sum()
prob = p_intersection/p_denominator
prob



0.2

In [ ]:
#Professor's Solution
num = ((df["Classes"] == 2) & (df["height"] < 7)).sum()
denum = (df["height"]<7).sum()
p = num/denum
p

0.2

**d) Compute the following probability. Use the Naive Bayes technique.**
$$P(label=l \ | \ intensity=2 \land height<6.5)$$

In [ ]:
#P(C|X) = P(X|C) P(C)/ P(X)
# Naive assumption is considering each X independent
# P(C|X) = P(x1|c)P(x2|c)P(x3|c)...P(c)  #we neglect the P(x)
# P(xi|c) = (num(xi,c)/len(df))/((num(c)/len(df))) = num(xi,c)/(num(c)
# P(c) = num(c)/ len(f)
for l in range(3):
  l1 = (df["Classes"] == l).sum()
  # p(intensity = 2 | label = l)
  p1 = ((df["Classes"] == l) & (df["intensity"] == 2)).sum()/l1
  # p(height < 6.5 |label = l)
  p2 = ((df["Classes"] == l) & (df["height"] < 6.5)).sum()/l1
  # p(label = l)
  pl = l1/len(df)
  result = p1*p2*pl
  print(f"likelihood({l}|x) = {result}")

likelihood(0|x) = 0.061538461538461556
likelihood(1|x) = 0.07692307692307693
likelihood(2|x) = 0.0


In [ ]:
import numpy as np
unique_classes = np.unique(df["Classes"])

for label in unique_classes:
  x = (df["intensity"] == 2)*(df["height"] < 6.5)
  p_intersection = (df[x]["Classes"] == label).sum()
  #following two lines returnes the same result
  #p_intersection = (df.loc[x, "Classes"]).sum()
  #p_intersection = ((df["Classes"] == 1)*(df["intensity"] == 2)*(df["height"] < 6.5)).sum()
  p_denominator = (df["height"] < 6.5).sum()
  prob = p_intersection/p_denominator
  print(f"probability of Class: {label} is: {prob} \n")


probability of Class: 0 is: 0.16666666666666666 

probability of Class: 1 is: 0.3333333333333333 

probability of Class: 2 is: 0.0 



**e) Normalize columns with Sklearn standard scaler, fit a random forest**

In [ ]:
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier


## 2) Working with Pandas and spatial data
**a) Load dataframe with Points Of Interest (POIs)**

In [ ]:
# This dictionary maps attributes in the table with correct data types
d_types = {'@type':str, '@lat':float, '@lon':float, 'amenity':str, 'name':str, 
           'shop':str, 'public_transport':str, 'highway':str}
# Read "./pois_all_info"
all_pois_df = pd.read_csv("pois_all_info.csv", sep='\t', index_col='@id', dtype=d_types)

FileNotFoundError: ignored

**b) Plot POIS on New-York map**

In [ ]:
def plot_map(pois_df):
    fig, ax = plt.subplots(figsize=(12,8))
    nyc_img = plt.imread('./New_York_City_Map.PNG')
    ax.imshow(nyc_img, zorder=0, extent=[-74.258, -73.7, 40.49,40.92])
    ax.scatter(??, s=1)
    plt.show()

plot_map(all_pois_df)

**c) Filter only POIS in NY municipality**
- Plot the result on a map

In [ ]:
# Read "./data/ny_municipality_pois_id.csv"
ny_pois_ids = pd.read_csv("ny_municipality_pois_id.csv", header=None)[0]

In [ ]:
pois_df = ??

In [ ]:
plot_map(pois_df)

**d) Count top-frequent public_transport types**

In [ ]:
top_freq = ??
top_freq

**e) Plot POIs with the two most frequent public transport types**

In [ ]:
## Plot POIs on the map
fig, ax = plt.subplots(figsize=(12,8))
nyc_img = plt.imread('./New_York_City_Map.PNG')
ax.imshow(nyc_img, zorder=0, extent=[-74.258, -73.7, 40.49,40.92])


## TODO:

plt.legend()
plt.show()